version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-crud-app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DATABASE_PASSWORD: ${MYSQL_ROOT_PASSWORD:-mysecretpassword}
      DB_NAME: crudnodejsmysql
      PORT: 3000
    volumes:
      - ./src:/usr/src/app/src 
      - /usr/src/app/node_modules 

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-mysecretpassword}
      MYSQL_DATABASE: crudnodejsmysql
    ports:
      - "3306:3306"
    
    volumes:
      - db_data:/var/lib/mysql
      - ./Database:/docker-entrypoint-initdb.d

    command: --default-authentication-plugin=mysql_native_password

volumes:
  db_data: