name: Terraform Infrastructure Deployment

# This workflow is only triggered manually (or via API) to ensure infrastructure changes are intentional.
# Developers must select 'plan' or 'apply' when running the workflow.
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform Action (plan or apply)'
        required: true
        type: choice
        default: 'plan'
        options:
        - plan
        - apply
      target_branch:
        description: 'Branch to run on (e.g., main)'
        required: true
        default: 'main'
        type: string

# Permissions block is crucial for OIDC authentication
permissions:
  id-token: write # Required for assuming the IAM role via OIDC
  contents: read  # Allow checkout

env:
  TF_WORKING_DIR: infra/aws
  # Use a dedicated secret for the S3 bucket name that stores the Terraform state
  TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET }} 
  # Use GitHub Variable for Region
  AWS_REGION: ${{ vars.AWS_REGION || 'us-east-1' }} 

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    # This job only runs if the user selects 'plan'
    if: github.event.inputs.action == 'plan'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.target_branch }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          # Pin version to match the requirement in main.tf
          terraform_version: 1.0.0 

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          # Assumes an IAM Role named 'GitHubActionsTerraformRole' for OIDC authentication
          role-to-assume: ${{ secrets.AWS_ROLE }}

      - name: Terraform Init (Configure S3 Backend)
        id: init
        # Initializing Terraform and pointing it to the S3 bucket for state management
        run: terraform init -backend-config="bucket=${{ env.TF_STATE_BUCKET }}" -backend-config="key=${{ vars.PROJECT_NAME || 'nodejs-crud-ecs' }}.tfstate"
        working-directory: ${{ env.TF_WORKING_DIR }}
        env:
          PROJECT_NAME: ${{ vars.PROJECT_NAME || 'nodejs-crud-ecs' }}

      - name: Terraform Plan
        id: plan
        # Pass the sensitive db_password from a GitHub Secret to prevent it from being logged directly
        run: terraform plan -out=tfplan -var-file=terraform.tfvars -var="db_password=${{ secrets.DB_MASTER_PASSWORD }}"
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: ${{ env.TF_WORKING_DIR }}/tfplan

  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: plan # Must pass the plan phase first
    # This job only runs if the user selects 'apply'
    if: github.event.inputs.action == 'apply'

    # CRITICAL: Manual Approval Gate - Requires a reviewer to approve before running the apply command
    environment: 
      name: production
      # Links back to the run page for easy plan review
      url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.target_branch }}
          
      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: ${{ env.TF_WORKING_DIR }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.0.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsTerraformRole 

      - name: Terraform Init (Configure S3 Backend)
        id: init
        # Need to initialize again to correctly connect to the remote S3 state
        run: terraform init -backend-config="bucket=${{ env.TF_STATE_BUCKET }}" -backend-config="key=${{ vars.PROJECT_NAME || 'nodejs-crud-ecs' }}.tfstate"
        working-directory: ${{ env.TF_WORKING_DIR }}
        env:
          PROJECT_NAME: ${{ vars.PROJECT_NAME || 'nodejs-crud-ecs' }}

      - name: Terraform Apply
        # Apply the pre-approved plan artifact
        run: terraform apply -auto-approve tfplan
        working-directory: ${{ env.TF_WORKING_DIR }}
